### ISSUE TITLE
use gitflow

### ISSUE THREAD

**Issue by rajilsaj** [kounkou/Template-Java#1]
want to taste gitflow in real life project @kounkou  and also Junit

**Comment by kounkou** [comment]
Perfect, I'll give the example tonight then when I am about to push the changes I made. 
The flow is 
create branch (local and push it to remote) -> make changes -> pull -> push remote (github), that's it !
I actually put in place JUnit with Gradle - Maven. I will push the changes tonight.
I like the way Gradle just goes and grabs the dependencies by itself.
Also, at the beginning I configured the manual building of the Tests... The building of the classes are trivial. I am not sure if we can add those info inside the Readme. Let's discuss on that when I push the changes tonight.

**Comment by kounkou** [comment]
So far so good, I added the contribution instructions with Pull Request #3 
check it out !
